# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField()),
                ('validate_status', models.CharField(choices=[('new', 0), ('rejected', 1), ('published', 2)], max_length=9)),
                ('validate_message', models.TextField()),
                ('url_published_news', models.TextField()),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField()),
                ('vk_token', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_phone_confirmed', models.BooleanField(default=False)),
                ('email', models.TextField(blank=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('auth_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='proposednews',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izjuminka.VKUser'),
        ),
    ]
