# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 04:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('validate_status', models.CharField(choices=[('new', 'new'), ('rejected', 'rejected'), ('published', 'published')], default='new', max_length=200)),
                ('validate_message', models.TextField(blank=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('vk_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vk_token', models.CharField(max_length=400)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_phone_confirmed', models.BooleanField(default=False)),
                ('email', models.TextField(blank=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('auth_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='proposednews',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='izjuminka.VKUser'),
        ),
    ]
