# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 07:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vk_id', models.CharField(max_length=100)),
                ('vk_token', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('source_post', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('vk_id_reference', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('validate_status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('in_progress', 'in_progress'), ('rewarded', 'rewarded')], default='pending', max_length=200)),
                ('validate_message', models.TextField(blank=True)),
                ('cash', models.FloatField(blank=True, default=0)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('vk_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('vk_token', models.CharField(max_length=400)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_phone_confirmed', models.BooleanField(default=False)),
                ('email', models.TextField(blank=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('auth_token', models.UUIDField(default=uuid.uuid4)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='proposednews',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='izjuminka.VKUser'),
        ),
        migrations.AddField(
            model_name='newsphoto',
            name='proposed_news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='izjuminka.ProposedNews'),
        ),
        migrations.AddField(
            model_name='account',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='izjuminka.ProposedNews'),
        ),
    ]
