# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('izjuminka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='izjuminka.ProposedNews')),
            ],
        ),
    ]
