# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izjuminka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposednews',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='vk_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
