# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izjuminka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposednews',
            name='cash',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
