# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izjuminka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposednews',
            name='source_post',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposednews',
            name='validate_status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('in_progress', 'in_progress'), ('rewarded', 'rewarded')], default='pending', max_length=200),
        ),
    ]
