# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 01:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izjuminka', '0002_auto_20171020_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
