# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('izjuminka', '0002_proposednews_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='vk_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
